version: '3'
services:
  bench:
    build:
      context: ./docker/bench
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-bench
    depends_on:
      - web
    networks:
      - frontend
  web:
    build:
      context: ./docker/web
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-web:nginx
    networks:
      - frontend
      - backend
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build:
      #context: ./docker/app/golang
      #context: ./docker/app/nodejs
      #context: ./docker/app/perl
      # context: ./docker/app/python
      # context: ./docker/app/ruby
      context: .
      dockerfile: ./docker/app/ruby/Dockerfile
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    #image: isucon7-qualifier-app:golang
    #image: isucon7-qualifier-app:nodejs
    #image: isucon7-qualifier-app:perl
    # image: isucon7-qualifier-app:python
    image: isucon7-qualifier-app:ruby
    networks:
      - backend
    depends_on:
       - db
    ports:
      - "5000"
    environment:
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      ISUBATA_DB_HOST: db
    volumes:
      - ./webapp/ruby:/home/isucon/isubata/webapp/ruby
      - bundle:/usr/local/bundle
    # command: sh -c "bundle install && bundle exec puma -p 5000 -t 10"
    command: sh -c "irb"
    tty: true
  db:
    build:
      context: ./docker/db
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-db
    ports:
      - "3306:3306"
    networks:
      - backend
    command: ["--character-set-server=utf8mb4"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #MYSQL_DATABASE: isubata
      #MYSQL_USER: isucon
      #MYSQL_PASSWORD: isucon
networks:
  frontend:
  backend:
volumes:
  bundle:
